config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #ログインページを作成
  resources :users, only: [:index]
  root 'users#index'
  
  
  
  #私の人生投稿ページを作成
  resources :mylives
  

  #私の財産投稿ページを作成
  resources :properties

  #お願いページを作成
  resources :requests

  #個別メッセージページを作成
  resources :messages
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord

    belongs_to :user


end

app/models/mylife.rb
class Mylife < ApplicationRecord
    mount_uploader :gallery, GalleryUploader
    belongs_to :user

end

app/models/property.rb
class Property < ApplicationRecord

    belongs_to :user

end

app/models/request.rb
class Request < ApplicationRecord

    belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #アソシエーション(1:多)
  has_many :messages



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  
    def index
    @messages = Message.all
    end

    
    def show
        @message = Message.find(params[:id])
    end
    
    def new
        @message= Message.new
    end

    def create
        @message = Message.new(message_params)
        @message.user_id = current_user.id
           
            if @message.save
              redirect_to messages_path
            else
              redirect_to :action => "new"
            end
          end
    
          


    def edit
            @message = Message.find(params[:id])
    end



    def update
        @message = Message.find(params[:id])
            if @message.update(message_params)
                redirect_to :action => "show", :id => @message.id
             else
                redirect_to :action => "new"
             end
            end
    
    
    def destroy
         Message.find(params[:id]).destroy
                redirect_to action: :index
    end

          private
          def message_params
            params.require(:message).permit(:user_id,:title,:body)
          end       
end

app/controllers/mylives_controller.rb
class MylivesController < ApplicationController
  before_action :authenticate_user!
  
    def index
      @mylives = Mylife.all
    end

    def show
        @mylife = Mylife.find(params[:id])
    end
    
    def new   
        @mylife = Mylife.new 
    end
    
    def create
        @mylife = Mylife.new(mylife_params)
        @mylife.user_id = current_user.id
        
           
            if @mylife.save
              redirect_to mylife_path(@mylife)
            else
              redirect_to :action => "show"
            end
          end
    

    def edit
            @mylife = Mylife.find(params[:id])
          end

    def update
            @mylife = Mylife.find(params[:id])
            if @mylife.update(mylife_params)
              redirect_to :action => "show", :id => @mylife.id
            else
              redirect_to :action => "new"
            end
          end      


    def destroy
            Mylife.find(params[:id]).destroy
                   redirect_to action: :index
          end

          private
          def mylife_params
            params.require(:mylife).permit(:user_id,:profile,:family,:life,:todo,:memories,:gallery)
          end      
    end    

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @properties = Property.all
  end

  
  
  def show
        @property = Property.find(params[:id])
    end
    
    def new
        @property = Property.new
    end

    def create
        @property = Property.new(property_params)
        @property.user_id = current_user.id
            if @property.save
              redirect_to property_path(@property)
            else
              redirect_to :action => "new"
            end
          end

    def edit
        @property = Property.find(params[:id])
    end

    
    def update
      @property = Property.find(params[:id])
          if @property.update(property_params)
              redirect_to :action => "show", :id => @property.id
           else
              redirect_to :action => "new"
           end
          end
          
          
    def destroy
            Property.find(params[:id]).destroy
                   redirect_to action: :index
          end

          private
          def property_params
            params.require(:property).permit(:user_id,:account,:balance,:real_estate,:value,:insurance,:insurance_proceeds,:debt,:debt_amount)
          end      
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!
  
    def index
      @requests = Request.all
    end
  
    def show
        @request = Request.find(params[:id])
    end
    
    def new
        @request = Request.new
    end

    def create
        @request = Request.new(request_params)
        @request.user_id = current_user.id
            if @request.save
              redirect_to request_path(@request)
            else
              redirect_to :action => "new"
            end
          end
    

    def edit
            @request = Request.find(params[:id])
    end



    def update
        @request = Request.find(params[:id])
            if @request.update(request_params)
                redirect_to :action => "show", :id => @request.id
             else
                redirect_to :action => "new"
             end
            end

    def destroy
            Request.find(params[:id]).destroy
                     redirect_to action: :index
            end   
    
    
    
    
            private
            def request_params
            params.require(:request).permit(:user_id,:illness,:care,:property,:funeral,:digital)
            end      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/mylives_helper.rb
module MylivesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/messages/edit.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
  <head><!--ページに表示されない情報(サイトの裏側の設定)-->
    <meta charset="utf-8">
    <title></title><!--ブラウザのタブのタイトルを指定-->
    <link rel="stylesheet" href="../../../../../../../../../stylesheets/messages.scss"><!--これであってるのか？-->
  </head>

  <div class="note_1_4">  


個別メッセージページ
<h2>タイトル</h2><br>
<%= form_with(model:@message,local:true) do |f| %>
    
    <div class="field">
    <%= f.label :body %>
    <%= f.text_field :title, :size => 140 %>
    </div>
    
    <h2>内容</h2><br>
    <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %>
    </div>
  
        
    <%= f.submit "投稿する" %>
  <% end %>

  <%= link_to 'ホームへ戻る', new_user_session_path %>

app/views/messages/index.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
  <head><!--ページに表示されない情報(サイトの裏側の設定)-->
    <meta charset="utf-8">
    <title></title><!--ブラウザのタブのタイトルを指定-->
    # <link rel="stylesheet"href="stylesheets/messages.scss" ><!--この一文なくても良さそう-->
  </head>

  <div class="note_1_1">  
<% @messages.each do |m| %>

  
        <div class="note_1">

        <div id="container">
        <div id="main">
              <%= link_to "投稿する", new_message_path %><br><br>
    
                  <div class="card" style="width: 18rem;">
                  <svg class="bd-placeholder-img card-img-top" width="100%" height="180" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image cap"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image cap</text></svg>
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text"></p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                  </div>
                </div>


                <%= m.title %><br>
                <%= m.body %><br>
                <%= link_to "ホームへ戻る", users_path %><br>
          
                <% if user_signed_in? && current_user.id == m.user_id %>  
                <%= link_to "編集する", edit_message_path(m.id) %><br>
                <%= button_to "削除する", message_path(m.id), method: :delete %>


        </div>
      </div>
   </div>
  
<% end %>
<% end %>

app/views/messages/new.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
  <head><!--ページに表示されない情報(サイトの裏側の設定)-->
    <meta charset="utf-8">
    <title></title><!--ブラウザのタブのタイトルを指定-->
    <link rel="stylesheet" href="../../../../../../../../../stylesheets/messages.scss"><!--これであってるのか？-->
  </head>

  <div class="note_1_3">  


個別メッセージページ
<h2>タイトル</h2><br>

<%= form_with(model:@message,local:true) do |f| %>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :title, :size => 140 %>
    </div>
    
    <h2>内容</h2><br>
    <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, :size => 140 %>
    </div>
  
        
    <%= f.submit "投稿する" %>
  <% end %>
  
  <%= link_to "個別メッセージページ一覧へ", messages_path %>
  <%= link_to "ホームへ戻る", users_path %><br>
  
  
 
  <!-- fはform_with(model:@message,local:true)を表している -->

app/views/messages/show.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
  <head><!--ページに表示されない情報(サイトの裏側の設定)-->
    <meta charset="utf-8">
    <title></title><!--ブラウザのタブのタイトルを指定-->
    <link rel="stylesheet" href="../../../../../../../../../stylesheets/messages.scss"><!--これであってるのか？-->
  </head>

  <div class="note_1_2">  

個別メッセージページ
<h2>タイトル</h2><br>
<%= @message.title %> 

<h2>内容</h2><br>
<%= @message.body %> <br>

<div class="note_1_2">


<div class="card" style="width: 18rem;">
  <svg class="bd-placeholder-img card-img-top" width="100%" height="180" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image cap"><title>Placeholder</title><rect width="100%" height="100%" fill="#868e96"/><text x="50%" y="50%" fill="#dee2e6" dy=".3em">Image cap</text></svg>
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

</div>

<%= link_to "編集する", edit_message_path(@message.id) %>
<%= link_to "投稿する", new_message_path(@message.id) %>
<%= link_to "個別メッセージページ一覧へ", messages_path(@message.id) %>
<%= link_to 'ホームへ戻る', new_user_session_path %>

app/views/mylives/index.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
  <head><!--ページに表示されない情報(サイトの裏側の設定)-->
    <meta charset="utf-8">
    <title></title><!--ブラウザのタブのタイトルを指定-->
    <link rel="stylesheet" href="../../../../../../../../../stylesheets/mylives.scss"><!--これであってるのか？-->
  </head>


  <div class="note_2_1">
<% @mylives.each do |m| %>
    
    <%= link_to "投稿する", new_mylife_path %><br><br>
    
    <%= m.profile %><br>
    <%= m.family %><br>
    <%= m.life %><br>
    <%= m.todo %><br>
    <%= m.memories %><br>
    <%= m.gallery %><br>
    <%= link_to "ホームへ戻る", users_path %><br>
    
    <% if user_signed_in? && current_user.id == m.user_id %>  
    <%= link_to "編集する", edit_mylife_path(m.id) %><br>
    <%= button_to "削除する", mylife_path(m.id), method: :delete %>
   


  </div>  
    <% end %>
    <% end %>

app/views/mylives/new.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
  <head><!--ページに表示されない情報(サイトの裏側の設定)-->
    <meta charset="utf-8">
    <title></title><!--ブラウザのタブのタイトルを指定-->
    <link rel="stylesheet" href="../../../../../../../../../stylesheets/mylives.scss"><!--これであってるのか？-->
  </head>


<div class="note_2_3">
私の人生ページ
<h2>プロフィール</h2><br>
<%= form_with(model:@mylife,local:true) do |f| %>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :profile, :size => 140 %>
    </div>
    
    <h2>家族</h2><br>
    <div class="field">
    <%= f.label :body %>
    <%= f.text_area :family, :size => 140 %>
    </div>
  
    <h2>死ぬまでにやりたいこと</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :todo, :size => 140 %>
    </div>
  
    <h2>思い出</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :memories, :size => 140 %>
    </div>
  
    <h2>ギャラリー</h2><br>
    
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :gallery, :size => 140 %>
    </div>
  
    <%= f.submit "投稿する" %>
  <% end %>

  <%= link_to "私の人生ページ一覧へ", mylives_path %>
  <%= link_to "ホームへ戻る", users_path %>
  
  </div>

app/views/mylives/show.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
  <head><!--ページに表示されない情報(サイトの裏側の設定)-->
    <meta charset="utf-8">
    <title></title><!--ブラウザのタブのタイトルを指定-->
    <link rel="stylesheet" href="../../../../../../../../../stylesheets/mylives.scss"><!--これであってるのか？-->
  </head>

  <div class="note_2_2">
私の人生ページ
<h2>プロフィール</h2><br>
<%= @mylife.profile %> 

<h2>家族</h2><br>
<%= @mylife.family %> 

<h2>人生</h2><br>
<%= @mylife.life %> 

<h2>死ぬまでにやりたいこと</h2><br>
<%= @mylife.todo %> 

<h2>思い出</h2><br>
<%= @mylife.memories %> 

<h2>ギャラリー</h2><br>
<%= image_tag(@mylife.gallery_url, width: 100) if @mylife.gallery.present? %><br>



<%= link_to "編集する", edit_mylife_path(@mylife.id) %>
<%= link_to "投稿する", new_mylife_path(@mylife.id) %>
<%= link_to "わたしの人生ページ一覧へ", mylives_path %>
<%= link_to 'ホームへ戻る', new_user_session_path %>

</div>

app/views/properties/edit.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
  <head><!--ページに表示されない情報(サイトの裏側の設定)-->
    <meta charset="utf-8">
    <title></title><!--ブラウザのタブのタイトルを指定-->
    <link rel="stylesheet" href="../../../../../../../../../stylesheets/mylives.scss"><!--これであってるのか？-->
  </head>

  <div class="note_3_4">


財産ページ
<h2>口座</h2><br>
<%= form_with(model:@property,local:true) do |f| %>

    <div class="field">
    <%= f.label :body %>
    <%= f.text_field :account, :size => 140 %>
    </div>
  
    <h2>残額</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_field :balance, :size => 140 %>
    </div>
  
    <h2>不動産</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_field :real_estate, :size => 140 %>
    </div>
  
    <h2>価値</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_field :value, :size => 140 %>
    </div>

    <h2>保険</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_field :insurance, :size => 140 %>
    </div>

    <h2>受け取り金額</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_field :insurance_proceeds, :size => 140 %>
    </div>
    
    <h2>負債</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_field :debt, :size => 140 %>
    </div>

    <h2>負債額</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_field :debt_amount, :size => 140 %>
    </div>
    
    <%= f.submit "投稿する" %>
  <% end %>
  <%= link_to "ホームへ戻る", users_path %><br>

app/views/properties/index.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
  <head><!--ページに表示されない情報(サイトの裏側の設定)-->
    <meta charset="utf-8">
    <title></title><!--ブラウザのタブのタイトルを指定-->
    <link rel="stylesheet" href="../../../../../../../../../stylesheets/properties.scss"><!--これであってるのか？-->
  </head>


  <div class="note_3_1">
<% @properties.each do |p| %>
    
    <%= link_to "投稿する", new_property_path %><br><br>
    
    <%= p.account %><br>
    <%= p. balance %><br>
    <%= p.real_estate %><br>
    <%= p.value %><br>
    <%= p.insurance %><br>
    <%= p.insurance_proceeds %><br>
    <%= p.debt %><br>
    <%= p.debt_amount %><br>
    <%= link_to "ホームへ戻る", users_path %><br>
   
    <% if user_signed_in? && current_user.id == p.user_id %>  
    <%= link_to "編集する", edit_property_path(p.id) %><br>
    <%= button_to "削除する", property_path(p.id), method: :delete %>
   
    

   </div> 
    <% end %>
    <% end %>

app/views/properties/new.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
  <head><!--ページに表示されない情報(サイトの裏側の設定)-->
    <meta charset="utf-8">
    <title></title><!--ブラウザのタブのタイトルを指定-->
    <link rel="stylesheet" href="../../../../../../../../../stylesheets/mylives.scss"><!--これであってるのか？-->
  </head>

  <div class="note_3_3">


私の持ち物ページ
<h2>口座</h2><br>
<%= form_with(model:@property,local:true) do |f| %>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :account, :size => 140 %>
    </div>
    
    <h2>残額</h2><br>
    <div class="field">
    <%= f.label :body %>
    <%= f.text_area :balance, :size => 140 %>
    </div>
  
    <h2>不動産</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :real_estate, :size => 140 %>
    </div>
  
    <h2>価値</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :value, :size => 140 %>
    </div>
  
    <h2>保険</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :insurance, :size => 140 %>
    </div>
    
    <h2>受け取り金額</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :insurance_proceeds, :size => 140 %>
    </div>
   
    <h2>負債</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :debt, :size => 140 %>
    </div>
    
    <h2>負債額</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :debt_amount, :size => 140 %>
    </div>
  


    <%= f.submit "投稿する" %>
  <% end %>

  <%= link_to "財産ページ一覧へ", mylives_path %>
  <%= link_to "ホームへ戻る", users_path %>
  
  

app/views/properties/show.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
  <head><!--ページに表示されない情報(サイトの裏側の設定)-->
    <meta charset="utf-8">
    <title></title><!--ブラウザのタブのタイトルを指定-->
    <link rel="stylesheet" href="../../../../../../../../../stylesheets/mylives.scss"><!--これであってるのか？-->
  </head>

  <div class="note_3_2">


財産ページ
<h2>口座</h2><br>
<%= @property.account %> 

<h2>残額</h2><br>
<%= @property.balance %> 

<h2>不動産</h2><br>
<%= @property.real_estate %> 

<h2>価値</h2><br>
<%= @property.value %> 

<h2>保険</h2><br>
<%= @property.insurance %> 

<h2>受け取り金額</h2><br>
<%= @property.insurance_proceeds %> 

<h2>負債</h2><br>
<%= @property.debt %> 

<h2>負債金額</h2><br>
<%= @property.debt_amount %> <br>

<%= link_to "編集する", edit_property_path(@property.id) %>
<%= link_to "投稿する", new_property_path(@property.id) %>
<%= link_to "財産ページ一覧へ", properties_path %>
<%= link_to 'ホームへ戻る', new_user_session_path %>

app/views/requests/edit.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
  <head><!--ページに表示されない情報(サイトの裏側の設定)-->
    <meta charset="utf-8">
    <title></title><!--ブラウザのタブのタイトルを指定-->
    <link rel="stylesheet" href="../../../../../../../../../stylesheets/requests.scss"><!--これであってるのか？-->
  </head>

<div class="note_4_4">
お願いページ
<h2>病気になったら</h2><br>
<%= form_with(model:@request,local:true) do |f| %>
  
  <div class="field">
  <%= f.label :body %>
  <%= f.text_field :illness, :size => 140 %>
  </div>
  
  <h2>介護が必要になったら</h2><br>
  <div class="field">
  <%= f.label :body %>
  <%= f.text_field :care, :size => 140 %>
  </div>

  <h2>財産について</h2><br>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :property, :size => 140 %>
  </div>

  <h2>葬儀について</h2><br>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :funeral, :size => 140 %>
  </div>

  <h2>デジタル関係</h2><br>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :digital, :size => 140 %>
  </div>
  
  
  <%= f.submit "投稿する" %>
<% end %>
<%= link_to "ホームへ戻る", users_path %><br>

app/views/requests/index.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
  <head><!--ページに表示されない情報(サイトの裏側の設定)-->
    <meta charset="utf-8">
    <title></title><!--ブラウザのタブのタイトルを指定-->
    <link rel="stylesheet" href="../../../../../../../../../stylesheets/requests.scss"><!--これであってるのか？-->
  </head>


  <div class="note_4_1">

  <% @requests.each do |r| %>

    <%= link_to "投稿する", new_request_path %><br><br>
    
    <%= r.illness %><br>
    <%= r.care  %><br>
    <%= r.property  %><br>
    <%= r.funeral  %><br>
    <%= r.digital  %><br>
    <%= link_to "ホームへ戻る", users_path %><br>
    
    <% if user_signed_in? && current_user.id == r.user_id %>  
    <%= link_to "編集する", edit_request_path(r.id) %><br>
    <%= button_to "削除する", request_path(r.id), method: :delete %>
    


  </div>  
    <% end %>
    <% end %>

app/views/requests/new.html.erb
<div class="note_4_3">
お願いページ
<h2>病気になったら</h2><br>
<%= form_with(model:@request,local:true) do |f| %>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :illness, :size => 140 %>
    </div>
    
    <h2>介護が必要になったら</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :care, :size => 140 %>
    </div>
  
    <h2>財産について</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :property, :size => 140 %>
    </div>
  
    <h2>葬儀について</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :funeral, :size => 140 %>
    </div>
  
    <h2>デジタル関係</h2><br>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :digital, :size => 140 %>
    </div>
    
    
    <%= f.submit "投稿する" %>
  <% end %>

  <%= link_to "お願いページ一覧へ", mylives_path %>
  <%= link_to "ホームへ戻る", users_path %>
  
  

app/views/requests/show.html.erb
<!DOCTYPE html> <!--　この文章がHTML文章であることを伝える要素です。-->
<html lang="ja"><!--言語の指定-->
  <head><!--ページに表示されない情報(サイトの裏側の設定)-->
    <meta charset="utf-8">
    <title></title><!--ブラウザのタブのタイトルを指定-->
    <link rel="stylesheet" href="../../../../../../../../../stylesheets/requests.scss"><!--これであってるのか？-->
  </head>

<div class="note_4_2">

お願いページ
<h2>病気になったら</h2><br>
<%= @request.illness %> 

<h2>介護が必要になったら</h2><br>
<%= @request.care %> 

<h2>財産について</h2><br>
<%= @request.property %> 

<h2>葬儀について</h2><br>
<%= @request.funeral %> 

<h2>デジタル関係</h2><br>
<%= @request.digital %> <br>



<%= link_to "編集する", edit_request_path(@request.id) %>
<%= link_to "投稿する", new_property_path(@request.id) %>
<%= link_to "お願いページ一覧へ", requests_path %>
<%= link_to 'ホームへ戻る', new_user_session_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>